apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-service-access-token-access
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - frontend
      - currencyservice
      - loadgenerator
      - productcatalogservice
      - checkoutservice
      - shippingservice
      - cartservice
      - redis-car
      - emailservice
      - paymentservice
      - recommendationservice
      - adservice
  file:
    matchDirectories:
    - dir: /run/secrets/kubernetes.io/serviceaccount/
      recursive: true
  action:
    Block