apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-pkg-mgmt-tools-exec
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - frontend
      - currencyservice
      - loadgenerator
      - productcatalogservice
      - checkoutservice
      - shippingservice
      - cartservice
      - redis-car
      - emailservice
      - paymentservice
      - recommendationservice
      - adservice
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
  action:
    Block