apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-5-net-icmp-audit
spec:
  severity: 8
  selector:
    matchLabels:
      env: benchmark
  network:
    matchProtocols:
    - protocol: icmp
  action:
    Audit