name: Terraform Apply on PR

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve

    - name: Get GKE Cluster Credentials
      run: gcloud container clusters get-credentials example-cluster --zone us-central1-c --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Run CLI Tool on GKE Cluster
      id: cli_output
      run: |
        output=$(kubectl get nodes -o wide)
        echo "CLI tool output:"
        echo "$output"
        echo "$output" > cli_output.txt
        echo "::set-output name=cli_output::$output"

    # - name: Checkout Wiki Repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: yourusername/your-repo.wiki
    #     path: ./wiki

    # - name: Update Wiki with CLI Output
    #   run: |
    #     echo "## CLI Tool Output" > ./wiki/CLI-Tool-Output.md
    #     echo "${{ steps.cli_output.outputs.cli_output }}" >> ./wiki/CLI-Tool-Output.md

    # - name: Commit and Push Changes
    #   run: |
    #     cd wiki
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add CLI-Tool-Output.md
    #     git commit -m "Update CLI Tool Output"
    #     git push
