name: Terraform Apply on PR

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials $(terraform output -raw kubernetes_cluster_name) --region us-central1
        echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

    # - name: Run CLI tool
    #   run: |
    #     # Replace 'your-cli-tool' with the actual CLI tool you want to run
    #     your-cli-tool --option value
