name: Terraform Apply on PR

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve

    - name: Get GKE Cluster Credentials
      run: gcloud container clusters get-credentials example-cluster --zone us-central1-c --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Run CLI Tool on GKE Cluster
      id: cli_output
      run: |
        git clone https://github.com/sratslla/KBC-KubeArmor-Benchmark-calculator.git
        cd KBC-KubeArmor-Benchmark-calculator
        go build -o KBC main.go
        output1 = $(kubectl apply -f https://raw.githubusercontent.com/sratslla/KBC-KubeArmor-Benchmark-calculator/main/manifests/kube-static-metrics.yaml)
        echo "$output1"
    #     output=$(cat final_report.md)
    #     echo "KBC tool output:"
    #     echo "$output"
    #     echo "$output" > kbc_output.txt
    #     echo "KBC_OUTPUT<<EOF" >> $GITHUB_ENV
    #     echo "$output" >> $GITHUB_ENV
    #     echo "EOF" >> $GITHUB_ENV

    # - name: Checkout Wiki Repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: sratslla/KBC-KubeArmor-Benchmark-calculator.wiki
    #     path: ./wiki
    #     token: ${{ secrets.GH_PAT }}
    
    # - name: Configure Git
    #   run: |
    #     git config --global user.email "action@github.com"
    #     git config --global user.name "GitHub Action"

    # - name: Update Wiki with CLI Output
    #   run: |
    #     echo "## CLI Tool Output" > ./wiki/CLI-Tool-Output.md
    #     echo "$CLI_OUTPUT" >> ./wiki/CLI-Tool-Output.md

    # - name: Commit and Push Changes
    #   env:
    #     GH_PAT: ${{ secrets.GH_PAT }}
    #   run: |
    #     cd wiki
    #     git add CLI-Tool-Output.md
    #     git commit -m "Update KBC Tool Output"
    #     git push https://GH_PAT@github.com/sratslla/KBC-KubeArmor-Benchmark-calculator.wiki.git
